backend:
  name: github
  repo: TON_PSEUDO_GITHUB/NOM_DE_TON_DEPOT # Exemple: Gilbert/Moi-Numerique
  branch: main # Ou master selon ton GitHub

media_folder: "assets/images/blog" # Où seront stockées tes images d'articles
public_folder: "/assets/images/blog"

collections:
  - name: "blog"
    label: "Articles du Jardin"
    [cite_start]folder: "blog/posts" # Dossier que tu as déjà créé [cite: 175]
    create: true # Autorise la création de nouveaux fichiers
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Image de couverture", name: "image", widget: "image" }
      - { label: "Résumé court", name: "description", widget: "text" }
      - { label: "Corps de l'article", name: "body", widget: "markdown" }
